version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: currency-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_HOST: '%'  # Allows root access from any host
      MYSQL_DATABASE: currency
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - currency-network
    command: --default-authentication-plugin=mysql_native_password  # Fixes auth issues
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  currency-exchange-service:
    build: .
    container_name: currency-exchange
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod  # <-- Fixed indentation (must align with other vars)
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/currency?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8000:8000"
    networks:
      - currency-network

volumes:
  mysql_data:

networks:
  currency-network: